SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=1;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=1;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS TOURIST_TELEGRAM_BOT DEFAULT CHARACTER SET utf8 ;
USE TOURIST_TELEGRAM_BOT ;

CREATE TABLE IF NOT EXISTS CITY (
id BIGINT NOT NULL AUTO_INCREMENT,
city_name VARCHAR(100) NOT NULL UNIQUE,
PRIMARY KEY (id)
)
ENGINE = InnoDB
AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS CITY_INFO (
info_id BIGINT NOT NULL AUTO_INCREMENT,
city_name VARCHAR(100) NOT NULL,
info TEXT NOT NULL,
PRIMARY KEY (info_id)
)

ENGINE = InnoDB
AUTO_INCREMENT = 1;

ALTER TABLE CITY_INFO
ADD FOREIGN KEY (city_name) REFERENCES city(city_name);


